old_templates = [
    "LARGE",
    "LARGE_RAPTOR",
    "LARGE_RAPTOR_HYBRID",
    "LARGE_GALLERY",
    "LARGE_GALLERY_ICO_SIMPLIFIED_TILE",
    "LARGE_GALLERY_ICO_SIMPLIFIED_TILE_INTL",
    "LARGE_GALLERY_INTL",
    "LARGE_NARROW",
    "LARGE_NARROW_ICO_SIMPLIFIED",
    "SMALL",
    "SMALL_NARROW",
    "SMALL_DENSE",
    "SMALL_DENSE_2",
    "DENSE_NATIVE",
    "DENSE_NATIVE_2",
    "CAROUSEL_LARGE",
    "CAROUSEL_SMALL",
    "CAROUSEL_NATIVE",
    "PRODUCT_LARGE",
    "PRODUCT_SMALL",
    "PRODUCT_SMALL_2",
    "SOV_CAROUSEL_LARGE_WEB",
    "SOV_CAROUSEL_LARGE_GALLERY_ICO_SIMPLIFIED_VIEW",
    "SOV_CAROUSEL_SMALL_WEB",
    "SOV_CAROUSEL_NATIVE",
    "SIS_HERO_ITEM",
    "VSE_HERO_ITEM_NATIVE",
    "LITE_LARGE_WEB",
    "LITE_SMALL_WEB",
    "LITE_NATIVE",
    "LARGE_GALLERY_WITH_SUB_SIGNALS",
    "LARGE_RAPTOR_WITH_SUB_SIGNALS",
    "SMALL_DENSE_WITH_GROUP_PRIORITIZATION",
    "SMALL_DENSE_2_WITH_GROUP_PRIORITIZATION",
    "DENSE_NATIVE_WITH_GROUP_PRIORITIZATION",
    "DENSE_NATIVE_2_WITH_GROUP_PRIORITIZATION",
    "LARGE_GALLERY_WITH_SUB_SIGNALS_AND_GROUP_PRIORITIZATION",
    "LARGE_RAPTOR_WITH_SUB_SIGNALS_AND_GROUP_PRIORITIZATION",
    "LARGE_GALLERY_INTL_WITH_GROUP_PRIORITIZATION",
    "LARGE_RAPTOR_WITH_GROUP_PRIORITIZATION",
]


assert len(old_templates) == 40, "Len should be 40"

migrated_templates = [
    "SOV_CAROUSEL_LARGE_WEB",
    "SOV_CAROUSEL_NATIVE",
    "SOV_CAROUSEL_SMALL_WEB",
    "SOV_CAROUSEL_BEST_SELLING",
    "SOV_CAROUSEL_BEST_SELLING_NATIVE",
    "SOV_CAROUSEL_BEST_SELLING_SHIPPING",
    "SOV_CAROUSEL_BEST_SELLING_SHIPPING_NATIVE",
    "SOV_CAROUSEL_STORES",
    "SOV_CAROUSEL_STORES_NATIVE",
    "SOV_CAROUSEL_CATEGORY_DISAMBIGUATION",
    "SOV_CAROUSEL_CATEGORY_DISAMBIGUATION_NATIVE",
    "SOV_CAROUSEL_VALUE_PROPS_AES",
    "SOV_CAROUSEL_VALUE_PROPS_NL",
    "SOV_CAROUSEL_VALUE_PROPS_TA",
    "SOV_CAROUSEL_VALUE_PROPS_AES_NATIVE",
    "SOV_CAROUSEL_VALUE_PROPS_NL_NATIVE",
    "SOV_CAROUSEL_VALUE_PROPS_TA_NATIVE",
    "EI_SMALL_WEB",
    "EI_LARGE_WEB",
    "EI_NATIVE",
    "SOV_CAROUSEL_VALUE_PROPS_TI",
    "SOV_CAROUSEL_VALUE_PROPS_BS",
    "SOV_CAROUSEL_VALUE_PROPS_TI_NATIVE",
    "SOV_CAROUSEL_VALUE_PROPS_BS_NATIVE",
]

assert len(migrated_templates) == 24, "Len should be 24"

diff = [x for x in old_templates if x not in migrated_templates]

print(diff)
print(len(diff))
